meta_name: "Solstice Fleuriste"
meta_title: "Fleuriste à Petite Île - La Réunion"
meta_description: "Artisan fleuriste dans le Sud Sauvage, je fleuris avec amour tous vos moments !"
meta_image: "solstice_logo.jpg" # should exist in `app/assets/images/`
